import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        "surface-variant": "#262627",
        "secondary-fixed-dim": "#dbb4ff",
        "on-background": "#ffffff",
        "on-primary-container": "#001867",
        outline: "#767576",
        "outline-variant": "#484849",
        "error-dim": "#d7383b",
        "on-secondary-fixed": "#4f0089",
        "error-container": "#9f0519",
        "surface-container-low": "#131314",
        "tertiary-fixed": "#00f1fd",
        "secondary-fixed": "#e5c6ff",
        "inverse-on-surface": "#565556",
        "inverse-surface": "#fcf8f9",
        "primary-container": "#859aff",
        "surface-dim": "#0e0e0f",
        "surface-container-highest": "#262627",
        background: "#0e0e0f",
        "on-primary": "#002283",
        "secondary-container": "#6f00be",
        "on-tertiary-fixed": "#004145",
        "primary-fixed": "#859aff",
        "on-surface": "#ffffff",
        "on-secondary-container": "#e9cdff",
        "tertiary-container": "#00f1fd",
        "primary-fixed-dim": "#718bff",
        "on-secondary-fixed-variant": "#7511c3",
        "on-surface-variant": "#adaaab",
        tertiary: "#96f8ff",
        "surface-container-lowest": "#000000",
        secondary: "#c180ff",
        "primary-dim": "#3e65ff",
        "on-error": "#490006",
        "on-primary-fixed": "#000000",
        error: "#ff716c",
        "inverse-primary": "#134af1",
        "on-secondary": "#33005b",
        "on-tertiary-container": "#00565a",
        "surface-container": "#1a191b",
        "tertiary-dim": "#00e2ed",
        "secondary-dim": "#9c48ea",
        surface: "#0e0e0f",
        "on-primary-fixed-variant": "#00207e",
        "on-tertiary": "#005f64",
        "surface-tint": "#97a9ff",
        primary: {
          DEFAULT: "#97a9ff",
          foreground: "#002283"
        },
        "tertiary-fixed-dim": "#00e2ed",
        "surface-container-high": "#201f21",
        "surface-bright": "#2c2c2d",
        "on-tertiary-fixed-variant": "#006065",
        "on-error-container": "#ffa8a3",
        // Keep shadcn required baselines
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        foreground: "hsl(var(--foreground))",
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
      },
      borderRadius: {
        xl: "3rem",
        lg: "2rem",
        md: "1rem",
        sm: "0.5rem",
      },
      fontFamily: {
        manrope: ["Manrope", "sans-serif"],
        inter: ["Inter", "sans-serif"],
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
      },
      keyframes: {
        "fade-in-up": {
          from: { opacity: "0", transform: "translateY(30px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "fade-in-up": "fade-in-up 0.8s cubic-bezier(0.16, 1, 0.3, 1) forwards",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
